language: go
go:
  - 1.8.x
install: make install-server
script:
  - make vet
  - $HOME/gopath/bin/goveralls -service=travis-ci
git:
  depth: 3
notifications:
  slack: pave-team:ybyoWBfz8v4zrsGs1lIgEcDi
  email: false
